spring:
  application:
    name: project
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/social-networks
    username: postgres
    password: Kaiou
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
project:
  app:
    jwtSecret: scscsccscsytuytuccuuuuuttttttydfhdhdjdjhwsefqs
    jwtExpirationMs: 86400000